### ISSUE TITLE
Under Users 

### ISSUE THREAD

**Issue by AlexEstoesta** [mlab817/ipms#16]
Just an observation upon reviewing the Users section, as my profile had indicated a short list of Owned PAPs but these are not written in text but in alpha numeric codes, and it was only my username that had that particular listing, as other Users don't have any listing in their respective Owned PAPs

**Comment by mlab817** [comment]
1. I opted for alphanumeric codes as they are shorter. They are for previews anyway. If you wish to view the full list of PAPs, you can visit the user's page.
2. The list of owned PAPs not showing for other users is expected since PAPs were filtered based on assigned office to you.

As for number 2, if you want we can limit both viewable users and offices to what is assigned to you. Let me know of your thoughts on this.
